name: Build WcfScan Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: latest

    # 新增步骤：直接下载并安装 .NET Framework 4.0 开发人员包
    - name: Download and Install .NET Framework 4.0 Developer Pack
      shell: powershell
      run: |
        $downloadUrl = "https://download.microsoft.com/download/9/5/B/95B00632-DD93-4E7F-A880-DA68305607B9/dotNetFx40_Full_setup.exe"
        $outputPath = "$env:TEMP\dotNetFx40_Full_setup.exe"

        Write-Host "Downloading .NET Framework 4.0 Full Redistributable (includes developer pack components)..."
        # 使用 Invoke-WebRequest 下载文件
        Invoke-WebRequest -Uri $downloadUrl -OutFile $outputPath -TimeoutSec 300 # 增加超时时间，避免下载大文件时超时

        Write-Host "Installing .NET Framework 4.0..."
        # 使用 Start-Process 静默安装，/q 或 /quiet 参数表示静默，/norestart 表示不重启
        Start-Process -FilePath $outputPath -ArgumentList "/q /norestart" -Wait -PassThru | Out-Null

        # 检查安装程序的退出代码。0 通常表示成功，3010 表示成功但需要重启。
        if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 3010) {
            Write-Error "Failed to install .NET Framework 4.0. Installer exited with code: $LASTEXITCODE"
            exit 1
        }
        Write-Host ".NET Framework 4.0 installed successfully."

    - name: Restore NuGet Packages
      run: msbuild WcfScan.sln /t:Restore

    - name: Build Solution
      run: msbuild WcfScan.sln /p:Configuration=Release /p:Platform="Any CPU" 

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WcfScan-Build
        path: WcfScan/bin/Release/
