name: Build WcfScan Project

on:
  push:
    branches:
      - main # 当代码推送到 main 分支时触发
  workflow_dispatch:

jobs:
  build:
    # 使用 Windows 运行器，因为它需要编译 .NET Framework/WCF 项目
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # 检出仓库代码到工作目录

    - name: Setup MSBuild
      # GitHub Actions 的 windows-latest 映像通常预装了 Visual Studio Build Tools
      # 但这个 action 可以确保 MSBuild 在 PATH 中并指定版本
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-version: latest # 使用最新版本的 MSBuild

    - name: Restore NuGet Packages # 恢复 NuGet 包依赖
      run: msbuild WcfScan.sln /t:Restore

    - name: Build Solution # 编译 WcfScan 解决方案
      run: msbuild WcfScan.sln /p:Configuration=Release /p:Platform="Any CPU" # 以 Release 配置编译

    - name: Upload Build Artifact # 上传编译好的文件作为产物
      uses: actions/upload-artifact@v3
      with:
        name: WcfScan-Build
        # 指定要上传的路径，这里假设 WcfScan 可执行文件在 WcfScan 项目的 bin/Release 目录下
        path: WcfScan/bin/Release/
        # 注意：如果你的项目结构不同，例如 WcfScan.sln 和 WcfScan 项目文件在同一目录
        # 路径可能是 bin/Release/
        # 你需要根据你的实际项目结构调整这个路径
