name: Build WcfScan Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild and .NET Framework 4.0 Targeting Pack
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: latest
        # 再次尝试通过 vs-installer-arguments 强制安装 .NET Framework 4.0 Targeting Pack
        # 加上 --force 参数，尝试确保安装成功
        # 加上 --noWeb 来尝试避免网络问题（虽然这里是特定组件安装）
        # 确保 --add 命令正确，并包含 --includeOptional 以防万一
        vs-installer-arguments: --add Microsoft.Component.NetFX.TargetPack.4.0 --includeOptional --force

    - name: Restore NuGet Packages
      run: msbuild WcfScan.sln /t:Restore

    - name: Build Solution
      run: msbuild WcfScan.sln /p:Configuration=Release /p:Platform="Any CPU" 

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WcfScan-Build
        path: WcfScan/bin/Release/
